### ISSUE TITLE
Create button to turn functionality off and on within popup.html

### ISSUE THREAD

**Issue by immattdavison** [immattdavison/NoMoreDomains#1]
A button/toggle-switch needs to be created within the popup which reflects within blockpage.js to allow users to visit domain registrars or not, depending on whether the toggle is toggled on or not, this could use `chrome.storage`

**Comment by Phoenix-031** [comment]
I would like to work on this...

**Comment by immattdavison** [comment]
You're welcome to make a fork and work on this, I can assign you now!

**Comment by immattdavison** [comment]
@Rutuj-Runwal is this an issue you would be interested in working on - not seen any activity from the currently assigned dev

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal is this an issue you would be interested in working on - not seen any activity from the currently assigned dev

Yes sure why not will gladly do.
Also to the previous pull request that you merged can you add "hacktoberfest-accepted" tag

Thanks.
