### ISSUE TITLE
Add cursor: pointer to button and improved css

### ISSUE THREAD

**Issue by nileshlad09** [immattdavison/NoMoreDomains#11]
![image](https://user-images.githubusercontent.com/89249015/193409169-e3a6f71d-ba4b-4bed-b98c-c98a744e5393.png)

I am new to open source if you liked my changes plz assigned this to me.

**Comment by immattdavison** [comment]
Feel free to work on this @nileshlad09

**Comment by Utkarshsharma1234** [comment]
I would like to fix the first issue

**Comment by immattdavison** [comment]
> I would like to fix the first issue

Please read the issue, this user had already asked for assignment

**Comment by Utkarshsharma1234** [comment]
Can I also give it a try

**Comment by immattdavison** [comment]
> Can I also give it a try

it is already a PR in review, apologies.

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.
