### ISSUE TITLE
JavaScript file link 

### ISSUE THREAD

**Issue by codeknight1** [immattdavison/NoMoreDomains#28]
I think the **javascript** file link should be  at the bottom of the page.

**Comment by immattdavison** [comment]
> I think the **javascript** file link should be  at the bottom of the page.

Hey @codeknight1 please provide some more information regarding this...

Which file? What is the reasoning, etc...

**Comment by thejeremias** [comment]
JS at the bottom speeds up page loading. You can also add the attribute defer to tag and leave it at the top.

**Comment by immattdavison** [comment]
Merged.
