### ISSUE TITLE
Auto update functionality 

### ISSUE THREAD

**Issue by Rutuj-Runwal** [immattdavison/NoMoreDomains#33]
The current implementation creates the rules using a local copy of `domains.json` as shown below:

```
fetch("/domains.json")
  .then((res) => res.json())
  .then((domains) => {
    chrome.declarativeNetRequest.updateDynamicRules({
         // Rules logic....

```

Insteas we can fetch the domains.json from this repo.So, replacing the local domains.json with it's online verison(raw github) and fetching it every day again to run it will create an "auto-update" logic. As any changes to domains.json will be reflected the next day in the dynamic ruleset.

Would be great if you could assign this to me.

**Comment by immattdavison** [comment]
This sounds great @Rutuj-Runwal however I'm unsure whether chrome allows the use of external files in MV3

**Comment by Rutuj-Runwal** [comment]
> This sounds great @Rutuj-Runwal however I'm unsure whether chrome allows the use of external files in MV3

Yes chrome allows the use of external files. We are treating it as a url and simply fetching the data using fetch 
I have already implemented something similar in my own extension that is live on chrome web store

**Comment by immattdavison** [comment]
> > This sounds great @Rutuj-Runwal however I'm unsure whether chrome allows the use of external files in MV3
> 
> Yes chrome allows the use of external files. We are treating it as a url and simply fetching the data using fetch I have already implemented something similar in my own extension that is live on chrome web store

Feel free to PR!

**Comment by Rutuj-Runwal** [comment]
@immattdavison Added the PR
