### ISSUE TITLE
Erroring keepAlive error log

### ISSUE THREAD

**Issue by immattdavison** [immattdavison/NoMoreDomains#36]
This error must be fixed.

![image](https://user-images.githubusercontent.com/80921257/193450708-0d105f7c-ded5-42a5-bde3-7a25a968c0c5.png)

**Comment by Alcadeus0** [comment]
hi can i work on this error?

**Comment by immattdavison** [comment]
> hi can i work on this error?

For sure, let me assign it to you!

**Comment by Alcadeus0** [comment]
how do i reproduce this bug?
should i just fork and run pop.html file?

**Comment by immattdavison** [comment]
> how do i reproduce this bug? should i just fork and run pop.html file?

Great Question.

You will need to add the extension to your chrome browser.

this should help: https://developer.chrome.com/docs/extensions/mv3/getstarted/

**Comment by Alcadeus0** [comment]
Alright gotcha. I'm almost done with resolving it. Will make a PR soon
