### ISSUE TITLE
Redirect to a warning page instead of Google

### ISSUE THREAD

**Issue by thejeremias** [immattdavison/NoMoreDomains#46]
I would like to develop a warning page to appear instead of Google homepage when the user tries to access a blocked registrar.

**Comment by Rutuj-Runwal** [comment]
@thejeremias Good idea, a warning page seems nice.
You can fork the repo and start working on the design just make sure that the theme matches the popup design of the extension.
Before creating a pull request show share a screenshot of your warning page design here.

**Comment by immattdavison** [comment]
> I would like to develop a warning page to appear instead of Google homepage when the user tries to access a blocked registrar.

While this is planned I think this should be developed with a structured idea in place. I have some ideas, I believe this page should show as a complete popup over the page with a button on it to turn NMD off for 30 minutes or  selected time frame. I will share more ideas later

**Comment by immattdavison** [comment]
@thejeremias what ideas did you have in mind?

**Comment by Dhravya** [comment]
I think @immattdavison's idea makes more sense.

**Comment by thejeremias** [comment]
> > I would like to develop a warning page to appear instead of Google homepage when the user tries to access a blocked registrar.
> 
> While this is planned I think this should be developed with a structured idea in place. I have some ideas, I believe this page should show as a complete popup over the page with a button on it to turn NMD off for 30 minutes or selected time frame. I will share more ideas later

Sounds good to me

**Comment by thejeremias** [comment]
Yeah

**Comment by aksha123-git** [comment]
I would to work on this issue please assign it to me

**Comment by immattdavison** [comment]
> I would to work on this issue please assign it to me

Assigning you.

**Comment by thejeremias** [comment]
I'm going to start developing now.

**Comment by immattdavison** [comment]
> I'm going to start developing now.

Highly appreciate this @thejeremias!

**Comment by thejeremias** [comment]
![image](https://user-images.githubusercontent.com/57194226/193858771-34fcb865-d2e5-42ef-82fc-885d0bde0f84.png)

Take a look at that.

**Comment by Rutuj-Runwal** [comment]
> ![image](https://user-images.githubusercontent.com/57194226/193858771-34fcb865-d2e5-42ef-82fc-885d0bde0f84.png)
> 
> Take a look at that.

Have you designed only the UI or the button actually works?

**Comment by immattdavison** [comment]
> ![image](https://user-images.githubusercontent.com/57194226/193858771-34fcb865-d2e5-42ef-82fc-885d0bde0f84.png)
> 
> Take a look at that.

Sure! I like that, does it work? If so you can make a PR and we'll get it merged providing it's functional

**Comment by immattdavison** [comment]
> It's almost done. I will try it.

Looking forward to your PR!
