### ISSUE TITLE
Improving Readme.md

### ISSUE THREAD

**Issue by BabyElias** [immattdavison/NoMoreDomains#47]
Enhance the appearance of Readme.md fo better visual appeal & also add Hacktoberfest 2022 accepted in the readme.

**Comment by arunkarthicknm** [comment]
I'd like to work on this, can you assign me?

**Comment by immattdavison** [comment]
> I'd like to work on this, can you assign me?

assigned

**Comment by arunkarthicknm** [comment]
Can you provide me the correct link of contributing guidelines page? @immattdavison

**Comment by shubhankarsharma876** [comment]
> Enhance the appearance of Readme.md fo better visual appeal & also add Hacktoberfest 2022 accepted in the readme.

I am willing to contribute to the readme file of this repository. So can you assign me with this issue. I believe I can ameliorate the documentation of this repository.

**Comment by PGautam27** [comment]
Hi @BabyElias I can improve the readme file as you've requested. I would also write comments so that it would be much easier for you to edit it, further if required. Could you assign this to me.
