### ISSUE TITLE
Create option to whitelist registrars

### ISSUE THREAD

**Issue by immattdavison** [immattdavison/NoMoreDomains#54]
An option should be added to whitelist certain domains as some domains do link to cloud services that are more than domain registrars. 

This should be a simple input on the page, potentially have a second page that the user can switch to on the popup to view their whitelisted registrars.

**Comment by mb-008** [comment]
I want to work on this issue.Can u assign me this and please include the label of hacktoberfest?

**Comment by immattdavison** [comment]
> I want to work on this issue.Can u assign me this and please include the label of hacktoberfest?

Assigning

**Comment by Rutuj-Runwal** [comment]
@immattdavison Seems like there is no progress here.
Can I work on this?

**Comment by immattdavison** [comment]
For sure!

**Comment by Rutuj-Runwal** [comment]
@immattdavison Can you add the hacktoberfest label to pr #77
