### ISSUE TITLE
Blocking domain sub frames

### ISSUE THREAD

**Issue by Rutuj-Runwal** [immattdavison/NoMoreDomains#68]
Some pages can embed the domains registrar as an iframe.
Add logic to block sub frame domains

**Comment by immattdavison** [comment]
I like this idea, do you want to work on it?

**Comment by Rutuj-Runwal** [comment]
> I like this idea, do you want to work on it? 

Yes you can assign

**Comment by immattdavison** [comment]
> > I like this idea, do you want to work on it? 
> 
> Yes you can assign 

Assigned
