### ISSUE TITLE
Add instructions to README.md about loading the extension on different browsers

### ISSUE THREAD

**Issue by codingfarhan** [immattdavison/NoMoreDomains#70]
Hi, I noticed it might be difficult for many people to use this extension because there are no instructions in the Readme file on how to use/load it in their browser. So adding the instructions to the Readme file (preferably with steps (and maybe screenshots too) of every step) should encourage more people to use the extension. 

The instructions should be written for all the browsers that are currently supported by this extension.

**Comment by immattdavison** [comment]
The reason this does not yet exist is because it will be published to the chrome web store when it is ready for general use.
