### ISSUE TITLE
Version bumps

### ISSUE THREAD

**Issue by Rutuj-Runwal** [immattdavison/NoMoreDomains#76]
Add rules in Contribution guidelines to update the version of extension in manifest.json with major pull requests(once with "enhancement" label)

**Comment by immattdavison** [comment]
> Add rules in Contribution guidelines to update the version of extension in manifest.json with major pull requests(once with "enhancement" label)

This isn't a bad shout, want me to assign you?

**Comment by Minetest-j45** [comment]
Can i do this?

**Comment by immattdavison** [comment]
Sure

**Comment by Minetest-j45** [comment]
This can be closed btw
