### ISSUE TITLE
Remove each whitelisted domain individually

### ISSUE THREAD

**Issue by immattdavison** [immattdavison/NoMoreDomains#78]
Currently all whitelisted domains are removed when the remove button is selected, this function should allow for each whitelisted domain to be deleted individually

**Comment by framadhita4** [comment]
can i work on this?

**Comment by immattdavison** [comment]
Sure!

**Comment by framadhita4** [comment]
thanks!

**Comment by immattdavison** [comment]
@Rutuj-Runwal as the other user assigned doesn't appear to have made a fork yet, would you be interested in working on this (I know we discussed it privately)

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal as the other user assigned doesn't appear to have made a fork yet, would you be interested in working on this (I know we discussed it privately)

Sure will start the development

**Comment by curator69** [comment]
has the issue assigned or needs to be?

**Comment by immattdavison** [comment]
> has the issue assigned or needs to be?

This issue is currently assigned.

**Comment by immattdavison** [comment]
> has the issue assigned or needs to be?

@curator69 This issue is open if its still something you wanted to work on?

**Comment by curator69** [comment]
@immattdavison sure will work on this, assign it to me

**Comment by immattdavison** [comment]
> @immattdavison sure will work on this, assign it to me

Assigned
