### ISSUE TITLE
Add custom blocking page

### ISSUE THREAD

**Issue by immattdavison** [immattdavison/NoMoreDomains#80]
We need a custom page to open when the extension recognises a NoMoreDomains blacklisted domain.

This should consist of the standard NoMoreDomains colours and a button to pause NoMoreDomains for the next 30 minutes. There should also be a link to the options page to whitelist a the selected domain.

**Comment by Rutuj-Runwal** [comment]
Can try this.
A quick question - 
> a button to pause NoMoreDomains for the next 30 minutes.

Does this mean NoMoreDomains will be completely paused or only for that website??

**Comment by immattdavison** [comment]
> Can try this. A quick question -
> 
> > a button to pause NoMoreDomains for the next 30 minutes.
> 
> Does this mean NoMoreDomains will be completely paused or only for that website??

I think completely pause NoMoreDomains, that would likely be the easier and most sensible option

**Comment by immattdavison** [comment]
Hey @Rutuj-Runwal, I don't suppose you were able to make any progress regarding this?

**Comment by Rutuj-Runwal** [comment]
> Hey @Rutuj-Runwal, I don't suppose you were able to make any progress regarding this

I was busy with some other projects
Have started on it now will be finished soon

**Comment by Rutuj-Runwal** [comment]
Hey @immattdavison this requires changing the structure of code significantly.
Won't be able to do it currently.

**Comment by immattdavison** [comment]
> Hey @immattdavison this requires changing the structure of code significantly.
> 
> Won't be able to do it currently.

Maybe for now a custom page with no additional functionality would be a good option Sind we add pausing at a later date?

**Comment by Rutuj-Runwal** [comment]
> > Hey @immattdavison this requires changing the structure of code significantly.
> > Won't be able to do it currently.
> 
> Maybe for now a custom page with no additional functionality would be a good option Sind we add pausing at a later date?

That is pretty much done then
Have added a basic block page that has some pause functionality.
It pauses the app but dosen't restart it after 30mins.

Will that do for the moment??

**Comment by immattdavison** [comment]
> > > Hey @immattdavison this requires changing the structure of code significantly.
> 
> > > Won't be able to do it currently.
> 
> > 
> 
> > Maybe for now a custom page with no additional functionality would be a good option Sind we add pausing at a later date?
> 
> 
> 
> That is pretty much done then
> 
> Have added a basic block page that has some pause functionality.
> 
> It pauses the app but dosen't restart it after 30mins.
> 
> 
> 
> Will that do for the moment??

Ah ok, no reason why that can't be added another time :)
