### ISSUE TITLE
add translation to README.md

### ISSUE THREAD

**Issue by CodeBreaker518** [immattdavison/NoMoreDomains#84]
Could I add a translation to readme.md to my nativa language? (Spanish)

**Comment by Rutuj-Runwal** [comment]
@CodeBreaker518 seems interesting.
If you can will you also help out with translations of https://github.com/RR-Adblocker

@immattdavison I think we can initiate translations to different languages
Google provides locale features to help your extension reach to all regions. Check here: https://developer.chrome.com/docs/webstore/i18n/

**Comment by Rutuj-Runwal** [comment]
@CodeBreaker518 seems interesting.
If you can will you also help out with translations of https://github.com/RR-Adblocker

@immattdavison I think we can initiate translations to different languages
Google provides locale features to help your extension reach to all regions. Check here: https://developer.chrome.com/docs/webstore/i18n/

**Comment by immattdavison** [comment]
> @CodeBreaker518 seems interesting.
> If you can will you also help out with translations of 
> https://github.com/Rutuj-Runwal/RR-Adblocker
> 
> @immattdavison I think we can initiate translations to different languages
> Google provides locale features to help your extension reach to all regions. Check here: https://developer.chrome.com/docs/webstore/i18n/
> 
> 

The only question I have is why translate the README when the extension is in English, also the issue this bring when maintaining and updating

**Comment by Rutuj-Runwal** [comment]
> > @CodeBreaker518 seems interesting.
> > If you can will you also help out with translations of 
> > https://github.com/Rutuj-Runwal/RR-Adblocker
> > 
> > @immattdavison I think we can initiate translations to different languages
> > Google provides locale features to help your extension reach to all regions. Check here: https://developer.chrome.com/docs/webstore/i18n/
> > 
> > 
> 
> The only question I have is why translate the README when the extension is in English, also the issue this bring when maintaining and updating 

Not just the readme I am talking about translation of the whole extension.
It will be a one time process and is easily maintainable. Also the benefits of this are quite scalable.

**Comment by immattdavison** [comment]
Have to consider as we add more options to things there will be new text

**Comment by anupeshverma** [comment]
!assign

**Comment by anupeshverma** [comment]
Kindly assign me this task i'm going to start to work upon this
