### ISSUE TITLE
[Enhancement] Update popup UI

### ISSUE THREAD

**Issue by abinjohn123** [immattdavison/NoMoreDomains#90]
I would love to give a go at updating the popup UI to make it look a bit more clean.

## Enhancement ideas
1. Reduce the width of the popup
2. Update settings icon
3. Include GitHub link at the footer
4. Update font

@immattdavison If this sounds good, please assign this to me. It would be great if you could add the `hacktoberfest` label as well.

**Comment by immattdavison** [comment]
> I would love to give a go at updating the popup UI to make it look a bit more clean.
> 
> 
> 
> ## Enhancement ideas
> 
> 1. Reduce the width of the popup
> 
> 2. Update settings icon
> 
> 3. Include GitHub link at the footer
> 
> 4. Update font
> 
> 
> 
> @immattdavison If this sounds good, please assign this to me. It would be great if you could add the `hacktoberfest` label as well.

This sounds great, feel free to make a PR!

**Comment by abinjohn123** [comment]
Awesome,  thank you!
