### ISSUE TITLE
[UI ENHANCEMENT] Making the Option Page UI wise better.

### ISSUE THREAD

**Issue by inclinedadarsh** [immattdavison/NoMoreDomains#95]
Below are some of the changes I can do to upgrade the UI of the Options Page.
- Give it a better header
- Change the fonts and font sizes
- Give the search bar a better look
- Fix the `whitelist` overflow
![image](https://user-images.githubusercontent.com/84132532/195977891-cceadd49-02db-4f7f-b9a6-f759513b9b93.png)

- Do some other changes

If this sounds good to you can you please assign this to me? Also, can you please add the `hacktoberfest` tag?

**Comment by inclinedadarsh** [comment]
## I will be publishing this change:
---
### Before:
![image](https://user-images.githubusercontent.com/84132532/195983070-70d5280d-5016-4ace-8a03-47e1af44162d.png)
---
### After:
![image](https://user-images.githubusercontent.com/84132532/195983149-a3ea2e27-e824-4c94-9e8b-f10b8c59fda3.png)
---
If this seems good then please assign this to me.
Thank You!

**Comment by immattdavison** [comment]
Hey @inclinedadarsh. While I love this you would need to comment out your URL, this is simply because if every contributor included a link to their website on the page it would lead to there being more links than extension. 

You will of course be referenced in our contributors. I hope this makes sense.

**Comment by immattdavison** [comment]
> Hey @inclinedadarsh. While I love this you would need to comment out your URL, this is simply because if every contributor included a link to their website on the page it would lead to there being more links than extension.
> 
> You will of course be referenced in our contributors. I hope this makes sense.

Oh wait I think i see now, you have whitelisted your own domain as an example

**Comment by inclinedadarsh** [comment]
Ohh, I won't be adding that. It's just a sample whitelisted website.

I did that so that I can show the remove button in both the cases.

**Comment by immattdavison** [comment]
> Ohh, I won't be adding that. It's just a sample whitelisted website.
> 
> I did that so that I can show the remove button in both the cases.

Makes sense, feel free to PR this!

**Comment by inclinedadarsh** [comment]
> > Hey @inclinedadarsh. While I love this you would need to comment out your URL, this is simply because if every contributor included a link to their website on the page it would lead to there being more links than extension.
> > 
> > You will of course be referenced in our contributors. I hope this makes sense.
> 
> Oh wait I think i see now, you have whitelisted your own domain as an example

Yes. It'll be the list of all the whitelisted websites. It's to show the UI of the new and old buttons in both the cases.

If this seems fine then please assign this to me.

**Comment by inclinedadarsh** [comment]
@immattdavison okay thanks!

Will make a PR in an hour maybe.

Thank You.
